version 0.9.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,19 @@
 #!/bin/sh
 
-echo "Configuring for a UNIX-alike platform"
+echo "Configuring for a UNIX-alike platform (sub-architecture: \"$R_ARCH\")";
 
-LOCALSYS_PATH=src$R_ARCH/Localsys.txt;
+# The location the Makevars will look for definitions
+if [ x"$R_ARCH" != x ]; then
+  mkdir -p ./src$R_ARCH;
+fi;
+
+LOCALSYS_PATH=./src$R_ARCH/Localsys.txt;
+touch $LOCALSYS_PATH;
+
+# Definitions should neither be empty nor default value 
+ISDEF_PKG_MOSEKHOME='( [ x"$PKG_MOSEKHOME" != x ] && [ x"$PKG_MOSEKHOME" != x"[MOSEK_HOME_PATH]" ] )';
+ISDEF_PKG_MOSEKLIB='( [ x"$PKG_MOSEKLIB" != x ] && [ x"$PKG_MOSEKLIB" != x"[MOSEK_LIB_FILE]" ] )';
+
 
 #
 # ATTEMPT 1: READ CONFIGURATION FROM ENVIRONMENT
@@ -10,52 +21,68 @@ LOCALSYS_PATH=src$R_ARCH/Localsys.txt;
 PKG_MOSEKHOME=$PKG_MOSEKHOME;
 PKG_MOSEKLIB=$PKG_MOSEKLIB;
 
-if ( [ x"$PKG_MOSEKHOME" = x ] || [ x"$PKG_MOSEKHOME" = x"[MOSEK_HOME_PATH]" ] ) && \
-   ( [ x"$PKG_MOSEKLIB"  = x ] || [ x"$PKG_MOSEKLIB"  = x"[MOSEK_LIB_FILE]"  ] ); then
+if (eval $ISDEF_PKG_MOSEKHOME) || (eval $ISDEF_PKG_MOSEKLIB); then
+  echo "Found variable definitions in environment";
+fi;
 
-  #
-  # ATTEMPT 2: READ CONFIGURATION FROM LOCALSYS FILE
-  #
+
+#
+# ATTEMPT 2: READ CONFIGURATION FROM LOCALSYS FILE
+#
+if (eval ! $ISDEF_PKG_MOSEKHOME) && (eval ! $ISDEF_PKG_MOSEKLIB); then
 
   # (1) Go through all lines,
   # (2) From those that start with PKG_MOSEKHOME=
   # (3) extract the RHS
   # (4) remove the carriage returns
   # (5) remove trailing spaces
-  PKG_MOSEKHOME=$(cat $LOCALSYS_PATH | grep "^PKG_MOSEKHOME" | sed 's/^PKG_MOSEKHOME=\(.*\)/\1/g' | sed 's/[\r]*$//g' | sed 's/[ ]*$//g');
-  PKG_MOSEKLIB=$(cat $LOCALSYS_PATH | grep "^PKG_MOSEKLIB" | sed 's/^PKG_MOSEKLIB=\(.*\)/\1/g' | sed 's/[\r]*$//g' | sed 's/[ ]*$//g');
 
+  PKG_MOSEKHOME=$(cat $LOCALSYS_PATH | grep "^PKG_MOSEKHOME" | sed 's/^PKG_MOSEKHOME=\(.*\)/\1/g' | sed 's/[\r]*$//g' | sed 's/[ ]*$//g' | sed 's/\"//g');
+  PKG_MOSEKLIB=$(cat $LOCALSYS_PATH | grep "^PKG_MOSEKLIB" | sed 's/^PKG_MOSEKLIB=\(.*\)/\1/g' | sed 's/[\r]*$//g' | sed 's/[ ]*$//g' | sed 's/\"//g');
+
+  if (eval $ISDEF_PKG_MOSEKHOME) || (eval $ISDEF_PKG_MOSEKLIB); then
+    echo "Found variable definitions in $LOCALSYS_PATH file";
+  fi;
 fi;
 
-if ( [ x"$PKG_MOSEKHOME" = x ] || [ x"$PKG_MOSEKHOME" = x"[MOSEK_HOME_PATH]" ] ) && \
-   ( [ x"$PKG_MOSEKLIB"  = x ] || [ x"$PKG_MOSEKLIB"  = x"[MOSEK_LIB_FILE]"  ] ); then
 
-  #
-  # ATTEMPT 3: GUESS CONFIGURATION FROM "mosek" command
-  #
+#
+# ATTEMPT 3: GUESS CONFIGURATION FROM "mosek" command
+#
+if (eval ! $ISDEF_PKG_MOSEKHOME) && (eval ! $ISDEF_PKG_MOSEKLIB); then
+
+  # (1) Find the full path of command 'mosek'
+  # (2) Remove the latter part 'bin/mosek*'
   PKG_MOSEKHOME=$(which mosek | sed 's/bin\/mosek*$//');
 
   # (1) Go through all mosek library files
-  # (2) From those that does not have additional specifiers (integers allowed)
-  # (3) Extract the integers if any, and add prefix 'mosek'
-  PKG_MOSEKLIB=$(find $PKG_MOSEKHOME -name 'libmosek*.so' | grep '\/libmosek\([0-9]*\).so*$' | sed 's/\(.*\)libmosek\([0-9]*\).so/mosek\2/g');
+  # (2) From those that does not have additional specifiers (integers/underscores allowed)
+  # (3) Extract the integers/underscores if any, and add prefix 'mosek'
+  PKG_MOSEKLIB=$(find $PKG_MOSEKHOME -name 'libmosek*.so' | grep '\/libmosek\([0-9,_]*\).so*$' | sed 's/\(.*\)libmosek\([0-9,_]*\).so/mosek\2/g');
 
+  if (eval $ISDEF_PKG_MOSEKHOME) || (eval $ISDEF_PKG_MOSEKLIB); then 
+    echo "Guessed variable definitions from shell command 'mosek'";
+  fi; 
 fi;
+
 
 #
 # EXIT IF A CONFIGURATION HAVE NOT BEEN READ
 #
-if [ x"$PKG_MOSEKHOME" = x ] || [ x"$PKG_MOSEKHOME" = x"[MOSEK_HOME_PATH]" ]; then
-  echo "*** Could not find variable 'PKG_MOSEKHOME' in configure-vars (configure.vars) argument ***";
-  echo "*** Could not find variable 'PKG_MOSEKHOME' in /src$R_ARCH/Localsys.txt file ***";
-  echo "*** Variable 'PKG_MOSEKHOME' not guessed from command 'mosek' in the current environment ***";
+if (eval ! $ISDEF_PKG_MOSEKHOME) && (eval ! $ISDEF_PKG_MOSEKLIB); then
+  echo "*** No variable 'PKG_MOSEKHOME' in environment - see configure-vars (configure.vars) argument ***";
+  echo "*** No variable 'PKG_MOSEKHOME' in $LOCALSYS_PATH file ***";
+  echo "*** Could not guess variable 'PKG_MOSEKHOME' from shell command 'mosek' ***";
   exit 1;
 fi;
 
-if [ x"$PKG_MOSEKLIB"  = x ] || [ x"$PKG_MOSEKLIB"  = x"[MOSEK_LIB_FILE]" ]; then
-  echo "*** Could not find variable 'PKG_MOSEKLIB' in configure-vars (configure.vars) argument ***";
-  echo "*** Could not find variable 'PKG_MOSEKLIB' in /src$R_ARCH/Localsys.txt file ***";
-  echo "*** Variable 'PKG_MOSEKHOME' not guessed from command 'mosek' in the current environment ***";
+if (eval ! $ISDEF_PKG_MOSEKHOME); then
+  echo "*** Variable 'PKG_MOSEKHOME' was not found here ***";
+  exit 1;
+fi;
+
+if (eval ! $ISDEF_PKG_MOSEKLIB); then
+  echo "*** Variable 'PKG_MOSEKLIB' was not found here ***";
   exit 1;
 fi;
 
@@ -68,8 +95,7 @@ fi;
 REMOVESLASHES=${PKG_MOSEKHOME##*[!/]};
 PKG_MOSEKHOME=${PKG_MOSEKHOME%$REMOVESLASHES};
 
-test -d $PKG_MOSEKHOME
-if [ $? != 0 ]; then
+if [ ! -d $PKG_MOSEKHOME ]; then
   echo "*** Variable 'PKG_MOSEKHOME' is not a directory: $PKG_MOSEKHOME ***"
   exit 1
 fi;
